### ISSUE TITLE
kakaotalk 웹뷰 이용시, 로그인 안되는 문제

### ISSUE THREAD

**Issue by songmilee** [Nexters/lettero-android#15]
## 이슈
- 카카오톡 웹뷰로 로그인 시, 카카오 계정을 확인하라고 뜹니다.
- 해당 부분으로 인해 접근이 불가하여 빠른 수정 부탁드립니다.

## 참조자
@dlwlrma-io 

## 참고 이미지
<img src="https://user-images.githubusercontent.com/9676685/111458656-0b866f00-875d-11eb-9a05-13b46dc51cfa.jpg" width="250px"/>
<img src="https://user-images.githubusercontent.com/9676685/111458667-0f19f600-875d-11eb-9a3a-5c320cfbdeab.jpg" width="250px"/>

**Comment by songmilee** [comment]
안드로이드 키해시 문제였습니다. 저희 릴리즈 키 별도 생성이 필요할 것 같네요.
릴리즈 키 생성 시, 부가적으로 필요한 점 있을까요? 없다면, 제가 별도로 생성하여 공유하겠습니다.

**Comment by dlwlrma-io** [comment]
릴리즈 키를 만들어 놓았었는데 아직 공유를 안 해드렸었네요. 퇴근 후 7시 경에 공유드려도 될까요???

**Comment by dlwlrma-io** [comment]
슬랙에 올려놨어요~
