### ISSUE TITLE
시스템 상태창과 앱바과 동시에 뜨는 버그

### ISSUE THREAD

**Issue by songmilee** [Nexters/lettero-android#16]
## 이슈
- introFragment 상에서 시스템 상태창과 앱바가 동시에 뜹니다.
- 처리가 불가능하다면, 앱바를 제거하는 쪽으로 가야할 것 같습니다.

## 재현 스텝
- 카카오로 로그인 버튼 클릭 -> 카카오톡 로그인 웹뷰 이동 -> 앱 복귀 -> 상태창 2개가 생성

## 참고자
@dlwlrma-io 

## 참고 이미지
<img src="https://user-images.githubusercontent.com/9676685/111459245-cf9fd980-875d-11eb-8119-ecf4cb820959.jpg" width="250px" />

**Comment by dlwlrma-io** [comment]
디바이스 별 이슈인지, 버전별 이슈인지 확인해보겠습니다~

**Comment by dlwlrma-io** [comment]
금일 회의 결과 다음 버전에 진행하는 것으로 결정했습니다~
